import Head from "next/head";
import dynamic from "next/dynamic";
import { withLayout } from "../../../components/Layout/withLayout";
import { NextPage } from "next";
import { useRouter } from "next/router";
import Loader2 from "../../../components/Loader/Loader2";
import { useUser } from "../../../components/Authenticate/UserContext";
const CommunityDetail = dynamic(() => import("../../../components/Community/CommunityDetail"), {
    loading: () => <Loader2 />,
});

const CommunityDetailPage: NextPage = () => {
    const router = useRouter();
    const { user } = useUser();

    if (user.email || user.phone_number) {
        return (
            <div>
                <Head>
                    <title>My Community</title>
                    <meta name="description" content="Generated by create next app" />
                    <link
                        rel="icon"
                        href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                    />
                </Head>
                <CommunityDetail communityId={router.query.community} />
            </div>
        );
    }
    return <Loader2 />;
};

export default withLayout(CommunityDetailPage);
