import Head from "next/head";
import { useState, ChangeEvent } from "react";
import { withLayout } from "../../../components/Layout/withLayout";

import { Box } from "@mui/material";
import { NextPage } from "next";
import styles from "../../../components/Community/Style/community.module.scss";
import Search from "../../../components/Search/Search";
import dynamic from "next/dynamic";
import CrossIcon from "../../../icons/CrossIcon";
import Loader2 from "../../../components/Loader/Loader2";
const CommunityCards = dynamic(() => import("../../../components/Community/CommunityCards"), {
    loading: () => <Loader2 />,
});
const Categories = dynamic(() => import("../../../components/Community/Categories"), {
    loading: () => <Loader2 />,
});
import Image from "next/image";
import { useUser } from "../../../components/Authenticate/UserContext";

const CommunityPage: NextPage = () => {
    const [search, setSearch] = useState<string>("");
    const [showFilter, setShowFilter] = useState(false);
    const { user } = useUser();

    const handleSearch = (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        const value = event.target.value;
        setSearch(value);
    };

    if (user.email || user.phone_number) {
        return (
            <Box sx={{ flexGrow: 1 }}>
                <Head>
                    <title>My Community</title>
                    <meta name="description" content="Generated by create next app" />
                    <link
                        rel="icon"
                        href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                    />
                </Head>
                {/* Header Section */}
                <div className={styles["community-header-section"]}>
                    <Image
                        src="https://images.prismic.io/loop-web-members/18a2d3c8-886f-4947-aca8-093c1d407915_community1.webp?auto=compress,format"
                        alt="https://images.prismic.io/loop-web-members/18a2d3c8-886f-4947-aca8-093c1d407915_community1.webp?auto=compress,format"
                        layout="fill"
                        objectFit="cover"
                    />
                    <div className={styles["community-header-title"]}>
                        <h1>Friendly, Safe & Welcoming Community of Lifelong Learners</h1>
                        <h6>Start joining the below listed communities</h6>
                    </div>
                </div>
                <div className={styles["community-heading-sortBy-holder"]}>
                    <div className={styles["community-heading"]}>Communities ({382} found)</div>
                    <div className={styles["community-search-Box"]}>
                        <Search handleSearch={handleSearch} value={search} placeholders={"Search community by name"} />
                    </div>
                    <div className={styles["community-dropdown"]}>
                        <span className={styles["community-dropdown-label"]}>Sort by: </span>
                        <select className={styles["community-dropdown2"]}>
                            <option value="">Newest First</option>
                        </select>
                    </div>
                    <button
                        className={styles["community-filter-btn"]}
                        onClick={() => {
                            setShowFilter(!showFilter);
                        }}
                    >
                        Communities Filters
                    </button>
                </div>
                <div className={styles["community-filters-card-holder"]}>
                    <div>
                        <div className={styles["community-filters"]}>
                            <div className={styles["community-search-title-holder"]}>
                                <div className={styles["community-title-cross-holder"]}>
                                    <div className={styles["community-title"]}>Search Community</div>
                                </div>
                                <Search
                                    handleSearch={handleSearch}
                                    value={search}
                                    placeholders={"Search community by name"}
                                />
                            </div>
                            <div className={styles["community-checkBox-holder"]}>
                                <div className={styles["community-title-clearAll-holder"]}>
                                    <div className={styles["community-title"]}>Categories</div>
                                    <div className={styles["community-clearAll"]}>Clear all</div>
                                </div>
                                <Categories />
                            </div>
                        </div>
                    </div>
                    {showFilter && (
                        <div className={styles["community-filters2"]}>
                            <div className={styles["community-search-title-holder"]}>
                                <div className={styles["community-title-cross-holder"]}>
                                    <div className={styles["community-title"]}>Community filters</div>
                                    <div
                                        onClick={() => {
                                            setShowFilter(!showFilter);
                                        }}
                                    >
                                        <CrossIcon />
                                    </div>
                                </div>
                                <div className={styles["community-sub-title"]}>Categories</div>
                                <Search handleSearch={handleSearch} value={search} placeholders={"Search categories"} />
                            </div>
                            <div className={styles["community-checkBox-holder"]}>
                                <Categories />
                                <div className={styles["community-title-clearAll-holder"]}>
                                    <div className={styles["community-title"]}>Apply filters</div>
                                    <div className={styles["community-clearAll"]}>Clear all</div>
                                </div>
                            </div>
                        </div>
                    )}
                    <CommunityCards communityDesginType={"communitycard"} />
                </div>
            </Box>
        );
    }
    return <Loader2 />;
};

export default withLayout(CommunityPage);
