// This file is generated by Slice Machine. Update with care!

import CareerPanel from './CareerPanel';
import Founder from './Founder';
import HeroPanel from './HeroPanel';
import Plan from './Plan';
import QuestionsAnswer from './QuestionsAnswer';

export {
	CareerPanel,
	Founder,
	HeroPanel,
	Plan,
	QuestionsAnswer,
};

export const components = {
	career_panel: CareerPanel,
	founder: Founder,
	hero_panel: HeroPanel,
	plan: Plan,
	questions_answer: QuestionsAnswer,
};
