import Head from "next/head";
import { NextPage } from "next";
import { Box } from "@mui/material";
import React from "react";
import { useRouter } from "next/router";
import Loader2 from "../components/Loader/Loader2";
import { withLayout } from "../components/Layout/withLayout";
import { useUser } from "../components/Authenticate/UserContext";

const Home: NextPage = () => {
    const router = useRouter();
    const { user } = useUser();

    // Based on user authenticated they will redirected to the List of Events
    if (user.email || user.phone_number) {
        router.push({
            pathname: "/UI/Events/",
        });
    }

    return (
        <Box sx={{ flexGrow: 1 }} className="layout-container">
            <Head>
                <title>login</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="icon"
                    href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                />
            </Head>
            <Loader2 />
        </Box>
    );
};

export default withLayout(Home);
