import Head from "next/head";
import { withLayout } from "../../../components/Layout/withLayout";
import { Box } from "@mui/material";
import { GetServerSideProps, NextPage } from "next";
import { ssrGetAllBuddies } from "../../../generated/page";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../../../components/Buddy/Style/buddyPage.module.scss";
import dynamic from "next/dynamic";
import Image from "next/image";
import { BuddyPageProps } from "../../../components/Buddy/Type";
import Loader2 from "../../../components/Loader/Loader2";
import { useUser } from "../../../components/Authenticate/UserContext";

const BuddyPlans = dynamic(() => import("../../../components/Buddy/BuddyPlans"), {
    loading: () => <Loader2 />,
});
const BuddyList = dynamic(() => import("../../../components/Buddy/BuddyList"), {
    loading: () => <Loader2 />,
});

const BuddyPage: NextPage<BuddyPageProps> = ({ data }) => {
    const router = useRouter();
    const { user, userDetails } = useUser();

    //useEffect will be triggered everytime  userDetails and router path change.
    useEffect(() => {
        // Below function is to perform routing to userDetails.buddyIntakeForm value.
        const checkIntakeFormCompletion = () => {
            if (userDetails.buddyIntakeForm) {
                if (userDetails.buddyIntakeForm === "Intake Form 1 Complete") {
                    router.push({
                        pathname: `/UI/Buddy/ThankYou/Home`,
                    });
                    return;
                } else if (userDetails.buddyIntakeForm === "Intake Form 2 Complete") {
                    router.push({
                        pathname: `/UI/Buddy/ThankYou/Family`,
                    });
                    return;
                } else if (userDetails.buddyIntakeForm === "Intake Form 3 Complete") {
                    router.push({
                        pathname: `/UI/Buddy/ThankYou/About`,
                    });
                    return;
                } else if (userDetails.buddy && userDetails.buddy !== "undefined") {
                    router.push({
                        pathname: `/UI/Buddy/${userDetails.buddy}`,
                    });
                    return;
                } else {
                    router.push({
                        pathname: `/UI/Buddy/ChooseYourBuddy`,
                    });
                    return;
                }
            } else {
                router.push({
                    pathname: `/UI/Buddy/ThankYou/Personal`,
                });
                return;
            }
        };
        // Below function will fetch rolesArr if exist then return single purchase role or client membership role.
        const checkBuddyRoles = (rolesArr: Array<string> | undefined | "") => {
            if (
                rolesArr &&
                rolesArr.some((role) => {
                    return (
                        role.trim().toLowerCase() === "the loop buddy client membership role" ||
                        role.trim().toLowerCase() === "the loop buddy client single purchase role"
                    );
                })
            )
                checkIntakeFormCompletion();
        };
        //Below function will be called if userDetails.roles then pass roles to checkBuddyRoles function.
        if (userDetails) {
            if (userDetails.roles) {
                const rolesArr = userDetails.roles.split(",");
                checkBuddyRoles(rolesArr);
            }
        }
    }, [userDetails, router]);

    if (user.email || user.phone_number) {
        return (
            <Box sx={{ flexGrow: 1 }} className="layout-container-fluid">
                <Head>
                    <title>My Buddy</title>
                    <meta name="description" content="Generated by create next app" />
                    <link
                        rel="icon"
                        href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                    />
                </Head>
                <div className={styles["buddy-page"]}>
                    <div className={styles["buddy-page-heading"]}>The LOOP Village Buddy Program</div>
                    <div className={styles["buddy-page-para"]}>
                        The LOOP Village Buddy Program is designed to compliment our weekly event schedule by giving you
                        access to a one-on-one Zoom call with a dedicated Village Buddy. Together you will develop a
                        friendship and have a go to person for companionship and conversation with a weekly
                        check-in.&nbsp;
                        <span>
                            Miriam explains her experience with her Village Buddy perfectly, read below testimonial from
                            Miriam.
                        </span>
                    </div>
                    <div className={styles["buddy-page-quote"]}>
                        {/* Below div is holding the image  */}
                        <div className={styles["buddy-page-quote-image1"]}>
                            <Image
                                src="https://images.prismic.io/loop-web-members/86d0d197-30bb-4242-b0c5-9ded3fa52162_Frame%2B454.webp?auto=compress,format"
                                alt="https://images.prismic.io/loop-web-members/86d0d197-30bb-4242-b0c5-9ded3fa52162_Frame%2B454.webp?auto=compress,format"
                                layout="fill"
                                objectFit="cover"
                            />
                        </div>
                        {/* Below div is holding the image  */}
                        <div className={styles["buddy-page-quote-image2"]}>
                            <Image
                                src="https://images.prismic.io/loop-web-members/f51ede7e-fa06-42a5-8ecb-f1aa2ba80ba6_%CE%93%C3%87%C2%A3.webp?auto=compress,format"
                                alt="https://images.prismic.io/loop-web-members/f51ede7e-fa06-42a5-8ecb-f1aa2ba80ba6_%CE%93%C3%87%C2%A3.webp?auto=compress,format"
                                layout="fill"
                                objectFit="cover"
                            />
                        </div>
                        <div className={styles["buddy-page-quote-para"]}>
                            <span>
                                During this unprecedented time of quarantine, the LOOP has become something of a very
                                special lifeline for me.
                            </span>
                            <span>
                                {" "}
                                I have never been much of a “joiner”, preferring “one on one” interactions. And being
                                able to spend time with Sandra over Zoom is a real treat. An interesting feature of LOOP
                                is that like being on a cruise, you can participate as much or as little as is
                                comfortable.
                            </span>
                            <span>I am enjoying the experience, and look forward to seeing Sandra each Tuesday.</span>

                            <span>—Miriam</span>
                        </div>
                    </div>
                </div>
                <BuddyPlans data={data} />
                <BuddyList data={data} />
            </Box>
        );
    }
    return <Loader2 />;
};

export default withLayout(BuddyPage);

export const getServerSideProps: GetServerSideProps = async (context) => {
    context.res.setHeader("Cache-Control", "public, s-maxage=10, stale-while-revalidate=59");
    const serverSideProps = await ssrGetAllBuddies.getServerPage(
        {
            variables: {},
        },
        context,
    );
    return {
        props: {
            ...serverSideProps.props,
        },
    };
};
