import Head from "next/head";
import { NextPage } from "next";
import { withLayout } from "../../../components/Layout/withLayout";
import { Box } from "@mui/material";
import styles from "../../../styles/thankyou/thankyou.module.scss";
import { useRouter } from "next/router";
import Image from "next/image";
import Loader2 from "../../../components/Loader/Loader2";
import { useUser } from "../../../components/Authenticate/UserContext";

const ThankYou: NextPage = () => {
    const router = useRouter();
    const { user } = useUser();

    if (user.email || user.phone_number) {
        return (
            <Box sx={{ flexGrow: 1 }} className="layout-container-fluid">
                <Head>
                    <title>Thank You</title>
                    <meta name="description" content="Generated by create next app" />
                    <link
                        rel="icon"
                        href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                    />
                </Head>
                <div className={styles["thankyou"]}>
                    <div className={styles["thankyou-pop-up"]}>
                        <Image
                            src={
                                "https://images.prismic.io/loop-web-members/609ffe6d-7235-40bb-9fd1-b12b399c3a07_thankyou-1.webp?auto=compress,format"
                            }
                            alt={"Thank_you"}
                            width={352}
                            height={229}
                            loading="lazy"
                        />
                        <div className={styles["thankyou-heading"]}>{router && router.query && router.query.title}</div>
                        {router && router.query && router.query.showText === "true" && (
                            <div className={styles["thankyou-para"]}>
                                Please check your <span>email inbox</span> for further communication.
                            </div>
                        )}
                        <button
                            onClick={() => {
                                router.push("/UI/Events");
                            }}
                            className={styles["thankyou-btn"]}
                        >
                            Return to Events
                        </button>
                    </div>
                </div>
            </Box>
        );
    }
    return <Loader2 />;
};

export default withLayout(ThankYou);
