import Head from "next/head";
import { NextPage } from "next";
import { Box } from "@mui/material";
import styles from "../../../../components/Authenticate/style/thankyou.module.scss";
import { useRouter } from "next/router";
import Link from "next/link";

const ThankYouPage: NextPage = () => {
    const router = useRouter();

    return (
        <Box sx={{ flexGrow: 1 }}>
            <Head>
                <title>Thank You</title>
                <meta name="description" content="Generated by create next app" />
                <link
                    rel="icon"
                    href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                />
            </Head>
            <div className={styles["thankyou"]}>
                <div className={styles["thankyou-container"]}>
                    <div className={styles["thankyou-pop-up"]}>
                        {/* <Image
                            src={
                                "https://images.prismic.io/loop-web-members/609ffe6d-7235-40bb-9fd1-b12b399c3a07_thankyou-1.webp?auto=compress,format"
                            }
                            alt={"Thank_you"}
                            width={352}
                            height={229}
                            loading="lazy"
                        /> */}
                        <div className={styles["thankyou-heading"]}>Your signup was successful.</div>
                        {router?.query?.signUpWithEmail === "true" ? (
                            <div className={styles["thankyou-para"]}>
                                Please check your email inbox for a verification link.
                            </div>
                        ) : (
                            <div
                                style={{
                                    display: "flex",
                                    justifyContent: "center",
                                    flexDirection: "column",
                                    alignItems: "center",
                                }}
                            >
                                <div className={styles["thankyou-para"]}>Please login from the button below.</div>
                                <Link href="/UI/Events/" passHref>
                                    <a target="_blank">
                                        <button className={styles["thankyou-btn"]}>Login</button>
                                    </a>
                                </Link>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </Box>
    );
};

export default ThankYouPage;
