import Head from "next/head";
import { withLayout } from "../../../../components/Layout/withLayout";
import { Box } from "@mui/material";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../../../../components/Buddy/Style/buddyThankYouPage.module.scss";
import dynamic from "next/dynamic";
import Image from "next/image";
import Loader2 from "../../../../components/Loader/Loader2";
import { useUser } from "../../../../components/Authenticate/UserContext";
const HomeDetails = dynamic(() => import("../../../../components/Buddy/ThankYou/HomeDetails"), {
    loading: () => <Loader2 />,
});
const FamilyDetails = dynamic(() => import("../../../../components/Buddy/ThankYou/FamilyDetails"), {
    loading: () => <Loader2 />,
});
const PersonalDetails = dynamic(() => import("../../../../components/Buddy/ThankYou/PersonalDetails"), {
    loading: () => <Loader2 />,
});
const AboutYou = dynamic(() => import("../../../../components/Buddy/ThankYou/AboutYou"), {
    loading: () => <Loader2 />,
});

const BuddyThankYouPage: NextPage = () => {
    const router = useRouter();
    const [tab, setTab] = useState<string | string[] | undefined>("Personal");
    const { user } = useUser();

    useEffect(() => {
        setTab(router.query.thankyou);
    }, [router.query.thankyou]);

    if (user.email || user.phone_number) {
        return (
            <Box sx={{ flexGrow: 1 }} className="layout-container-fluid">
                <Head>
                    <title>Thankyou-{tab}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link
                        rel="icon"
                        href="https://images.prismic.io/loop-web-members/4df527d2-6dfb-4c78-9499-a0facef03af3_looptech.webp?auto=compress,format"
                    />
                </Head>
                <div className={styles["buddy-thankyou"]}>
                    <div className={styles["buddy-thankyou-box"]}>
                        <div className={styles["buddy-thankyou-box-image"]}>
                            <Image
                                src="https://images.prismic.io/loop-web-members/cc999661-890b-43ef-90b6-92cd9798ab05_thankyou.png?auto=compress,format"
                                alt="https://images.prismic.io/loop-web-members/cc999661-890b-43ef-90b6-92cd9798ab05_thankyou.png?auto=compress,format"
                                layout="fill"
                                objectFit="cover"
                            />
                        </div>
                        <p className={styles["buddy-thankyou-box-para1"]}>
                            You have successfully purchased your Village Buddy
                        </p>
                        <p className={styles["buddy-thankyou-box-para2"]}>
                            Before we ask you to choose your buddy we have a few questions we would like you to answer.
                            By answering with as much detail as possible we will be able to shape your Village Buddy
                            experience. Your chosen Buddy will be able to see what your interests are, what you are
                            comfortable talking about and more importantly what topics you don’t wish to discuss.{" "}
                        </p>
                    </div>
                    <div className={styles["buddy-thankyou-para"]}>
                        Once you have completed this intake form we will ask you to choose your Buddy, this form will be
                        emailed to you as well, just in case you don’t have time to complete it right now.
                    </div>
                    <div className={styles["buddy-thankyou-tabs-holder"]}>
                        <div className={styles["buddy-thankyou-tabs"]}>
                            <div className={styles["buddy-thankyou-tab-active"]}>Personal details</div>
                            <div
                                className={
                                    tab === "Home" || tab === "Family" || tab === "About"
                                        ? styles["buddy-thankyou-tab-active"]
                                        : styles["buddy-thankyou-tab"]
                                }
                            >
                                Home details
                            </div>
                            <div
                                className={
                                    tab === "Family" || tab === "About"
                                        ? styles["buddy-thankyou-tab-active"]
                                        : styles["buddy-thankyou-tab"]
                                }
                            >
                                Family details
                            </div>
                            <div
                                className={
                                    tab === "About" ? styles["buddy-thankyou-tab-active"] : styles["buddy-thankyou-tab"]
                                }
                            >
                                About you
                            </div>
                        </div>
                    </div>
                    <div className={styles["buddy-thankyou-tab-body"]}>
                        {tab === "Personal" && <PersonalDetails />}
                        {tab === "Home" && <HomeDetails />}
                        {tab === "Family" && <FamilyDetails />}
                        {tab === "About" && <AboutYou />}
                    </div>
                </div>
            </Box>
        );
    }
    return <Loader2 />;
};

export default withLayout(BuddyThankYouPage);
